name: Resize Images

on: push

jobs:
  scale_images:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Run scaling step
      id: scale
      uses: turtlesec-no/scale-images@v1.0
      with:
       image-folder: 'images'

    - name: No images found - scaling output 0
      if: steps.scale.outputs.scaled == '0'
      run: echo "No images found"

    - name: All images were already scaled - scaling output 1
      if: steps.scale.outputs.scaled == '1'
      run: echo "All images were already scaled"

    - name: Some/all images scaled - scaling output 2
      if: steps.scale.outputs.scaled == '2'
      run: echo "Some/all images scaled"

    - name: Commit image files
      working-directory: images
      if: ${{ github.ref_name == 'main' }}
      run: | 
        git config user.email "bot@turtlesec.no"
        git config user.name "Turtle Bot (GitHub Action)"
        if [[ "$( git status --porcelain)" != "" ]]; then
          git add -A
          git commit -m "Updated image files"
          git push
        fi

    - name: Store images
      uses: actions/upload-artifact@v3
      if: steps.scale.outputs.scaled == '2' && ${{ github.ref_name != 'main' }}
      with:
        retention-days: 1
        name: images
        path: images/
