name: Resize Images

on: push

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Run scaling step
      id: scale
      uses: actions/scale-images@master
      with:
       image-folder: 'images'

    - name: Check scaling output 0
      if: steps.scale.outputs.scaled == '0'
      run: echo "No images found"

    - name: Check scaling output 1
      if: steps.scale.outputs.scaled == '1'
      run: echo "All images were already scaled"

    - name: Check scaling output 2
      if: steps.scale.outputs.scaled == '2'
      run: echo "Some images were scaled"

    - name: Commit image files
      working-directory: images
      run: | 
        git config user.email "bot@turtlesec.no"
        git config user.name "Turtle Bot (GitHub Action)"
        if [[ "$( git status --porcelain *.jpg)" != "" ]]; then
          git add -A *.jpg
          git commit -m "Updated image files"
          git push
        fi
